#!/usr/bin/env python

import argparse
import sys
import netCDF4
import numpy
from eoPlanet import Planet
from eoColorCells import ColorCells
from eoDateTimes import DateTimes
from eoScene import Scene

def main(ar):

    parser = argparse.ArgumentParser(description='Visualize earth data')
    parser.add_argument('-s', dest='standard_name', default='', help='Select variable by standard name')
    parser.add_argument('-f', dest='filename', default='', help='File name')
    args = parser.parse_args()

    if not len(args.filename):
        print('ERROR: must supply a file name')
        sys.exit(1)

    if not len(args.standard_name):
        print('ERROR: must select a variable by its standard name')
        sys.exit(2)

    filename = args.filename
    varStandardName = args.standard_name

    color = ColorCells(filename=filename, varStandardName=varStandardName, level=0)

    planet = Planet(level=0)

    dateTimes = DateTimes(dts=color.getDateTimes(), pos=(800, 900), size=52, color=(0.2, 0.2, 0.2))

    s = Scene()
    s.setBackground(0.7, 0.7, 0.7)
    s.addPipelines([planet, color, dateTimes])
    s.start()


if __name__ == '__main__':
    main(sys.argv)




